pipeline {
    agent any
    triggers {
        cron('H/5 * * * *')
    }
    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir() // remove all files from workspace
            }
        }
        stage('Setup Environment') {
            steps {
                script {
                    echo 'Setting up environment...'
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run API Tests') {
            steps {
                script {
                    echo 'Running API tests...'
                    sh '''
                        . venv/bin/activate
                        pytest --alluredir=allure-results -m api
                    '''
                }
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
        }
    }
}
