pipeline {
    agent any
    triggers {
        cron('0 9,21 * * *')
    }
    stages {
        stage('Setup Environment') {
            steps {
                script {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run UI Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest --alluredir=allure-results -m uitests
                '''
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
        }
    }
}